import React, { useState } from 'react';
import { ShieldCheck, KeyRound, AlertCircle, ArrowRight, X } from 'lucide-react';
import { useAuth } from '../context/AuthContext';

export default function MfaChallengeModal({ isOpen, onClose, challengeData, onSuccess }) {
  const { completeMfaLogin } = useAuth();
  const [code, setCode] = useState('');
  const [isBackupMode, setIsBackupMode] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  if (!isOpen || !challengeData) return null;

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError(null);

    const cleanCode = code.trim();
    if (!cleanCode) {
      setError('Please enter your verification code.');
      return;
    }

    if (!isBackupMode && cleanCode.length !== 6) {
      setError('Please enter a valid 6-digit verification code.');
      return;
    }

    setLoading(true);
    try {
      await completeMfaLogin(challengeData.temp_token, cleanCode);
      if (onSuccess) {
        onSuccess();
      }
    } catch (err) {
      setError(err.message || 'Invalid or expired verification code.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-xs animate-in fade-in duration-200">
      <div 
        className="relative w-full max-w-md bg-white dark:bg-slate-900 rounded-3xl border border-slate-200 dark:border-slate-800 shadow-2xl p-6 sm:p-8"
        onClick={(e) => e.stopPropagation()}
      >
        <button
          onClick={onClose}
          className="absolute top-5 right-5 p-2 rounded-full text-slate-400 hover:text-slate-600 dark:hover:text-slate-200 hover:bg-slate-100 dark:hover:bg-slate-800 transition"
          aria-label="Close"
        >
          <X className="w-5 h-5" />
        </button>

        <div className="text-center">
          <div className="w-14 h-14 rounded-2xl bg-gradient-to-tr from-emerald-600 to-teal-500 mx-auto flex items-center justify-center shadow-lg shadow-emerald-500/20 mb-4 text-white">
            <ShieldCheck className="w-7 h-7" />
          </div>
          <h3 className="text-xl font-black text-slate-900 dark:text-slate-100 tracking-tight">
            Two-Factor Authentication
          </h3>
          <p className="mt-1 text-xs text-slate-500 dark:text-slate-400">
            {isBackupMode ? (
              <span>Enter one of your 8-character single-use emergency backup recovery codes.</span>
            ) : (
              <span>
                Enter the 6-digit rolling code generated by your Authenticator app (e.g. Google Authenticator, Authy).
              </span>
            )}
          </p>
        </div>

        {error && (
          <div className="mt-4 p-3.5 rounded-xl bg-rose-50 dark:bg-rose-950/40 border border-rose-200 dark:border-rose-800 text-rose-700 dark:text-rose-300 text-xs font-semibold flex items-center gap-2">
            <AlertCircle className="w-4 h-4 shrink-0" />
            <span>{error}</span>
          </div>
        )}

        <form onSubmit={handleSubmit} className="mt-6 space-y-4">
          <div>
            <label className="text-xs font-bold text-slate-700 dark:text-slate-300 block mb-1">
              {isBackupMode ? 'Recovery Code' : '6-Digit Authenticator Code'}
            </label>
            <input
              type="text"
              autoFocus
              required
              maxLength={isBackupMode ? 12 : 6}
              value={code}
              onChange={(e) => {
                const val = isBackupMode ? e.target.value.toUpperCase() : e.target.value.replace(/\D/g, '');
                setCode(val);
              }}
              placeholder={isBackupMode ? 'ABCD-EFGH' : '000000'}
              className="w-full text-center tracking-[0.4em] text-lg font-mono font-black py-3 rounded-xl border border-slate-200 dark:border-slate-700 focus:outline-emerald-500 bg-slate-50/50 dark:bg-slate-800 text-slate-900 dark:text-slate-100 placeholder:tracking-normal placeholder:font-sans placeholder:text-sm"
            />
          </div>

          <div className="text-center pt-1">
            <button
              type="button"
              onClick={() => {
                setIsBackupMode(!isBackupMode);
                setCode('');
                setError(null);
              }}
              className="text-xs font-bold text-emerald-600 dark:text-emerald-400 hover:text-emerald-700 dark:hover:text-emerald-300 inline-flex items-center gap-1 cursor-pointer"
            >
              <KeyRound className="w-3.5 h-3.5" />
              <span>{isBackupMode ? 'Use Authenticator Code instead' : 'Lost device? Use Recovery Code'}</span>
            </button>
          </div>

          <button
            type="submit"
            disabled={loading}
            className="w-full py-3 px-4 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white font-bold text-xs shadow-md transition-all flex items-center justify-center gap-2 cursor-pointer disabled:opacity-50"
          >
            <span>{loading ? 'Verifying Challenge...' : 'Verify & Continue'}</span>
            <ArrowRight className="w-4 h-4" />
          </button>
        </form>
      </div>
    </div>
  );
}
